name: unstable

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04

    container:
      image: debian:latest
      volumes:
        - /proc:/proc
      options: --privileged

    steps:
    - uses: actions/checkout@v2
    
    - name: Install needed packages
      run: apt update

    - name: Build ISO
      run: ./build.sh etc/terraform.conf

    - uses: actions/upload-artifact@v2
      with:
        name: HornbillOS 22.10
        path: builds/
    
